### ISSUE TITLE
refactor test to fixtures

### ISSUE THREAD

**Issue by kawa2287** [kawa2287/title-belt-nhl#11]
This isn't a bad way to do it, but you could also make the JSON array a pytest fixture in conftest.py inside `tests/`:

```py
@pytest.fixture
def league_schedule():
    return [
      {
        "id": 2023010045,
        "season": 20232024,
        # ... all the other stuff
      }
    ]
```
And then in the tests you can just say
```py
def test_current_title_belt_holder(league_schedule):
    # use league_schedule the same way you're using `leagueSchedule` below)
```
because the fixtures defined in conftest.py are available to any tests in the directory (you just pass them by name): https://docs.pytest.org/en/stable/reference/fixtures.html#conftest-py-sharing-fixtures-across-multiple-files

_Originally posted by @elffaW in https://github.com/kawa2287/title-belt-nhl/pull/9#discussion_r1744232939_

**Comment by elffaW** [comment]
I think this is done with #19?
